add wave -position insertpoint {*clock*}
add wave -position insertpoint {*io_start*}
add wave -position insertpoint {*io_inputBit*}
add wave -position insertpoint {*io_outResult*}
add wave -position insertpoint {*io_outResultValid*}
add wave -position insertpoint {*buffer_0*}
add wave -position insertpoint {*buffer_1*}
add wave -position insertpoint {*buffer_2*}
add wave -position insertpoint {*buffer_3*}
add wave -position insertpoint {*buffer_4*}
add wave -position insertpoint {*buffer_5*}
add wave -position insertpoint {*buffer_6*}
add wave -position insertpoint {*buffer_7*}
add wave -position insertpoint {*buffer_8*}
add wave -position insertpoint {*buffer_9*}
add wave -position insertpoint {*counter*}
add wave -position insertpoint {*outputCounter*}
add wave -position insertpoint {*isPassedDelta*}
add wave -position insertpoint {*isOutputValid*}
add wave -position insertpoint {*state*}
add wave -position insertpoint {*outputBuffer*}
